In [1]:
"""
This notebook is the base analysis and clearning of the dataset.
"""

'\nThis notebook is the base analysis and clearning of the dataset.\n'

In [23]:
# Imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plot

In [72]:
# Reading the file

df_full = pd.read_csv('C:/Users/Kura/ddi/projects/launches/data/space_devs_launches_2010_2026.csv')

In [73]:
# Printing out the columns (there are WAY too many)

for col in df_full.columns:
    print(col)

id
url
name
response_mode
slug
launch_designator
last_updated
net
window_end
window_start
infographic
probability
weather_concerns
failreason
hashtag
mission
webcast_live
program
orbital_launch_attempt_count
location_launch_attempt_count
pad_launch_attempt_count
agency_launch_attempt_count
orbital_launch_attempt_count_year
location_launch_attempt_count_year
pad_launch_attempt_count_year
agency_launch_attempt_count_year
status.id
status.name
status.abbrev
status.description
net_precision.id
net_precision.name
net_precision.abbrev
net_precision.description
image.id
image.name
image.image_url
image.thumbnail_url
image.credit
image.license.id
image.license.name
image.license.priority
image.license.link
image.single_use
image.variants
launch_service_provider.response_mode
launch_service_provider.id
launch_service_provider.url
launch_service_provider.name
launch_service_provider.abbrev
launch_service_provider.type.id
launch_service_provider.type.name
rocket.id
rocket.configuration.response_mode
rocket.configuration.id
rocket.configuration.url
rocket.configuration.name
rocket.configuration.families
rocket.configuration.full_name
rocket.configuration.variant
pad.id
pad.url
pad.active
pad.agencies
pad.name
pad.image.id
pad.image.name
pad.image.image_url
pad.image.thumbnail_url
pad.image.credit
pad.image.license.id
pad.image.license.name
pad.image.license.priority
pad.image.license.link
pad.image.single_use
pad.image.variants
pad.description
pad.info_url
pad.wiki_url
pad.map_url
pad.latitude
pad.longitude
pad.country.id
pad.country.name
pad.country.alpha_2_code
pad.country.alpha_3_code
pad.country.nationality_name
pad.country.nationality_name_composed
pad.map_image
pad.total_launch_count
pad.orbital_launch_attempt_count
pad.fastest_turnaround
pad.location.response_mode
pad.location.id
pad.location.url
pad.location.name
pad.location.celestial_body.response_mode
pad.location.celestial_body.id
pad.location.celestial_body.name
pad.location.celestial_body.type.id
pad.location.celestial_body.type.name
pad.location.celestial_body.diameter
pad.location.celestial_body.mass
pad.location.celestial_body.gravity
pad.location.celestial_body.length_of_day
pad.location.celestial_body.atmosphere
pad.location.celestial_body.image.id
pad.location.celestial_body.image.name
pad.location.celestial_body.image.image_url
pad.location.celestial_body.image.thumbnail_url
pad.location.celestial_body.image.credit
pad.location.celestial_body.image.license.id
pad.location.celestial_body.image.license.name
pad.location.celestial_body.image.license.priority
pad.location.celestial_body.image.license.link
pad.location.celestial_body.image.single_use
pad.location.celestial_body.image.variants
pad.location.celestial_body.description
pad.location.celestial_body.wiki_url
pad.location.celestial_body.total_attempted_launches
pad.location.celestial_body.successful_launches
pad.location.celestial_body.failed_launches
pad.location.celestial_body.total_attempted_landings
pad.location.celestial_body.successful_landings
pad.location.celestial_body.failed_landings
pad.location.active
pad.location.country.id
pad.location.country.name
pad.location.country.alpha_2_code
pad.location.country.alpha_3_code
pad.location.country.nationality_name
pad.location.country.nationality_name_composed
pad.location.description
pad.location.image.id
pad.location.image.name
pad.location.image.image_url
pad.location.image.thumbnail_url
pad.location.image.credit
pad.location.image.license.id
pad.location.image.license.name
pad.location.image.license.priority
pad.location.image.license.link
pad.location.image.single_use
pad.location.image.variants
pad.location.map_image
pad.location.longitude
pad.location.latitude
pad.location.timezone_name
pad.location.total_launch_count
pad.location.total_landing_count
net_precision
pad.image
mission.id
mission.name
mission.type
mission.description
mission.image
mission.orbit.id
mission.orbit.name
mission.orbit.abbrev
mission.orbit.celestial_body.response_mode
mission.orbit.celestial_body.id
mission.orbit.celestial_body.name
mission.agencies
mission.info_urls
mission.vid_urls
image
pad.country
mission.orbit
pad.location.country
mission.image.id
mission.image.name
mission.image.image_url
mission.image.thumbnail_url
mission.image.credit
mission.image.license.id
mission.image.license.name
mission.image.license.priority
mission.image.license.link
mission.image.single_use
mission.image.variants
pad.location.image

In [90]:
# Shortening the dataset by specifying what columns to keep

cols_to_keep = ['id', 'name', 'launch_designator', 'net', 'window_end', 'window_start','failreason',
                'status.name', 'status.abbrev', 'launch_service_provider.name', 'launch_service_provider.type.name',
                'rocket.configuration.name', 'rocket.configuration.full_name', 'rocket.configuration.families',
                'mission.name', 'mission.type', 'mission.orbit.name', 'mission.orbit.abbrev', 'pad.name', 'pad.location.name',
                'pad.country.name', 'pad.latitude', 'pad.longitude']

df = df_full[cols_to_keep].copy()

In [91]:
# Renaming columns so they are easier to use

df = df.rename(columns={
    "id": "launch_id",
    "name": "launch_name",
    "launch_designator": "launch_designator",
    "net": "launch_datetime",
    "window_end": "launch_window_end",
    "window_start": "launch_window_start",
    "failreason": "failure_reason",

    "status.name": "status",
    "status.abbrev": "status_abbrev",

    "launch_service_provider.name": "launch_provider",
    "launch_service_provider.type.name": "provider_type",

    "rocket.configuration.name": "rocket_name",
    "rocket.configuration.full_name": "rocket_full_name",
    "rocket.configuration.families": "rocket_family",

    "mission.name": "mission_name",
    "mission.type": "mission_type",
    "mission.orbit.name": "orbit",
    "mission.orbit.abbrev": "orbit_abbrev",

    "pad.name": "launch_pad",
    "pad.location.name": "launch_location",
    "pad.country.name": "launch_country",
    "pad.latitude": "pad_latitude",
    "pad.longitude": "pad_longitude"
})

# Convert date columns to datetime
df['launch_datetime'] = pd.to_datetime(df['launch_datetime'], errors='coerce')
df['launch_window_start'] = pd.to_datetime(df['launch_window_start'], errors='coerce')
df['launch_window_end'] = pd.to_datetime(df['launch_window_end'], errors='coerce')

# Create useful time columns for analysis
df['year'] = df['launch_datetime'].dt.year
df['month'] = df['launch_datetime'].dt.month
df['quarter'] = df['launch_datetime'].dt.quarter

In [92]:
# Saving cleaned dataset
df.to_csv('C:/Users/Kura/ddi/projects/launches/data/space_devs_launches_cleaned.csv', index=False)

In [93]:
# Quick look at the cleaned dataset

df.head()

,launch_id,launch_name,launch_designator,launch_datetime,launch_window_end,launch_window_start,failure_reason,status,status_abbrev,launch_provider,...,orbit,orbit_abbrev,launch_pad,launch_location,launch_country,pad_latitude,pad_longitude,year,month,quarter
0,bb643566-508a-4f3a-a701-85669d11e2b3,Long March 3C | Compass-G1,2010-001,2010-01-16 16:12:04+00:00,2010-01-16 16:12:04+00:00,2010-01-16 16:12:04+00:00,NaN,Launch Successful,Success,China Aerospace Science and Technology Corpora...,...,NaN,NaN,Launch Complex 2 (LC-2),"Xichang Satellite Launch Center, People's Repu...",China,28.245504,102.026768,2010,1,1
1,470aff2b-3cc8-4e98-9ada-d511828b4676,Proton-M / Briz-M Enhanced | Globus-1M #12L (R...,2010-002,2010-01-28 00:18:00+00:00,2010-01-28 00:18:00+00:00,2010-01-28 00:18:00+00:00,NaN,Launch Successful,Success,Khrunichev State Research and Production Space...,...,NaN,NaN,81/24 (81P),"Baikonur Cosmodrome, Republic of Kazakhstan",Kazakhstan,46.071001,62.984999,2010,1,1
2,cb3977fe-3ef4-46d2-8bc9-65a0d9cef07a,Soyuz-U | Progress M-04M (36P),2010-003,2010-02-03 03:45:30+00:00,2010-02-03 03:45:30+00:00,2010-02-03 03:45:30+00:00,NaN,Launch Successful,Success,Russian Federal Space Agency (ROSCOSMOS),...,NaN,NaN,1/5,"Baikonur Cosmodrome, Republic of Kazakhstan",Kazakhstan,45.920000,63.342000,2010,2,1
3,80db2215-04bd-4d16-b998-311fb73db4fe,Space Shuttle Endeavour / OV-105 | STS-130,2010-004,2010-02-08 09:14:08+00:00,2010-02-08 09:14:08+00:00,2010-02-08 09:14:08+00:00,NaN,Launch Successful,Success,United Space Alliance,...,Low Earth Orbit,LEO,Launch Complex 39A,"Kennedy Space Center, FL, USA",United States of America,28.608227,-80.604282,2010,2,1
4,7e4160fc-c9d5-4db6-b9b1-166408741f0e,Atlas V 401 | SDO (Solar Dynamics Observatory),2010-005,2010-02-11 15:23:00+00:00,2010-02-11 15:23:00+00:00,2010-02-11 15:23:00+00:00,NaN,Launch Successful,Success,United Launch Alliance,...,Enhanced Geostationary Transfer Orbit,Enhanced-GTO,Space Launch Complex 41,"Cape Canaveral SFS, FL, USA",United States of America,28.583410,-80.583036,2010,2,1

In [94]:
# There are a LOT of null values in this dataset
# Many are to be expected, such as failure_reason but others may be dropped with if necessary in analysis

print(df.shape)
df.info()

# Dropped probability as that's probably only needed for weather analysis, and many null values

(2469, 26)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2469 entries, 0 to 2468
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   launch_id            2469 non-null   object
 1   launch_name          2469 non-null   object
 2   launch_designator    2211 non-null   object
 3   launch_datetime      2469 non-null   datetime64[ns, UTC]
 4   launch_window_end    2469 non-null   datetime64[ns, UTC]
 5   launch_window_start  2469 non-null   datetime64[ns, UTC]
 6   failure_reason       78 non-null     object
 7   status               2469 non-null   object
 8   status_abbrev        2469 non-null   object
 9   launch_provider      2469 non-null   object
 10  provider_type        2469 non-null   object
 11  rocket_name          2469 non-null   object
 12  rocket_full_name     2469 non-null   object
 13  rocket_family        2469 non-null   object
 14  mission_name         2196 non-null   object
 15  mission_type         2196 non-null   object
 16  orbit                2183 non-null   object
 17  orbit_abbrev         2146 non-null   object
 18  launch_pad           2469 non-null   object
 19  launch_location      2469 non-null   object
 20  launch_country       2461 non-null   object
 21  pad_latitude         2469 non-null   float64
 22  pad_longitude        2469 non-null   float64
 23  year                 2469 non-null   int32
 24  month                2469 non-null   int32
 25  quarter              2469 non-null   int32
dtypes: datetime64[ns, UTC](3), float64(2), int32(3), object(18)
memory usage: 472.7+ KB

In [95]:
# Checking for duplicates

print(f"Full row duplicates: {df.duplicated().sum()}")
print(f"Launch id duplicates: {df['launch_id'].duplicated().sum()}")
print(f"Launch name duplicates: {df['launch_name'].duplicated().sum()}")

# Checks actual duplicates
# df[df["launch_name"].duplicated(keep=False)].sort_values("launch_name")

# Decided not to drop these rows as the IDs are distinct and are likely separate launch events

Full row duplicates: 0
Launch id duplicates: 0
Launch name duplicates: 20

In [96]:
df.sample(10)

,launch_id,launch_name,launch_designator,launch_datetime,launch_window_end,launch_window_start,failure_reason,status,status_abbrev,launch_provider,...,orbit,orbit_abbrev,launch_pad,launch_location,launch_country,pad_latitude,pad_longitude,year,month,quarter
913,0b161194-00d2-4e42-81b0-22e4c50d2b87,Atlas V 551 | AEHF-6,2020-022,2020-03-26 20:18:00+00:00,2020-03-26 20:57:00+00:00,2020-03-26 18:57:00+00:00,NaN,Launch Successful,Success,United Launch Alliance,...,Geostationary Transfer Orbit,GTO,Space Launch Complex 41,"Cape Canaveral SFS, FL, USA",United States of America,28.583410,-80.583036,2020,3,1
431,db2dfb3b-e744-42ac-9cd8-ed936ad9a882,Falcon 9 v1.1 | SpX CRS-6,2015-021,2015-04-14 20:10:41+00:00,2015-04-14 20:10:41+00:00,2015-04-14 20:10:41+00:00,NaN,Launch Successful,Success,SpaceX,...,Low Earth Orbit,LEO,Space Launch Complex 40,"Cape Canaveral SFS, FL, USA",United States of America,28.561941,-80.577357,2015,4,2
613,f92e838b-3997-4b21-9b7e-86c057e80efb,Ariane 5 ECA | ViaSat-2 & EUTELSAT 172B,2017-029,2017-06-01 23:45:07+00:00,2017-06-02 00:45:00+00:00,2017-06-01 23:45:00+00:00,NaN,Launch Successful,Success,Arianespace,...,Geostationary Transfer Orbit,GTO,Ariane Launch Area 3,"Guiana Space Centre, French Guiana",French Guiana,5.239000,-52.768000,2017,6,2
1319,bcae88ce-1d12-4198-9d62-0cd5f024a986,Long March 2D | Gaofen-5-01A,2022-165,2022-12-08 18:31:00+00:00,2022-12-08 19:05:00+00:00,2022-12-08 18:22:00+00:00,NaN,Launch Successful,Success,China Aerospace Science and Technology Corpora...,...,Sun-Synchronous Orbit,SSO,Launch Complex 9,"Taiyuan Satellite Launch Center, People's Repu...",China,38.863128,111.589567,2022,12,4
684,6d2526ef-2a0a-4bc8-a717-afa27210d203,Long March 2C | 3 x Yaogan-30,2018-011,2018-01-25 05:39:04+00:00,2018-01-25 05:51:00+00:00,2018-01-25 05:31:00+00:00,NaN,Launch Successful,Success,China Aerospace Science and Technology Corpora...,...,Low Earth Orbit,LEO,Launch Complex 3 (LC-3/LA-1),"Xichang Satellite Launch Center, People's Repu...",China,28.247059,102.029008,2018,1,1
26,2ead3d70-ac04-40ee-b4a6-dfecfe519ee5,Falcon 9 v1.0 | Dragon Spacecraft Qualificatio...,2010-026,2010-06-04 18:45:00+00:00,2010-06-04 18:45:00+00:00,2010-06-04 18:45:00+00:00,NaN,Launch Successful,Success,SpaceX,...,Low Earth Orbit,LEO,Space Launch Complex 40,"Cape Canaveral SFS, FL, USA",United States of America,28.561941,-80.577357,2010,6,2
2399,b48e32c5-3776-4684-a956-5ea4df032e90,Spectrum | ΣYNDEO-3,NaN,2026-12-31 00:00:00+00:00,2026-12-31 00:00:00+00:00,2026-12-31 00:00:00+00:00,NaN,To Be Determined,TBD,Isar Aerospace,...,Low Earth Orbit,LEO,Orbital Launch Pad,Andøya Spaceport,Norway,69.108400,15.589500,2026,12,4
1438,d454be53-3a0c-4b7f-82b9-50ee4a4b48b0,Zhuque-2 | Flight 2,2023-097,2023-07-12 01:00:00+00:00,2023-07-12 03:14:00+00:00,2023-07-12 00:53:00+00:00,NaN,Launch Successful,Success,LandSpace,...,Sun-Synchronous Orbit,SSO,Launch Area 96A,"Jiuquan Satellite Launch Center, People's Repu...",China,40.914910,100.245488,2023,7,3
1757,95a9c95c-1a30-4b34-8b11-16e765a26eb6,Soyuz 2.1a | Kosmos 2579 (Bars-M No. 6),2024-197,2024-10-31 07:51:31+00:00,2024-10-31 09:00:00+00:00,2024-10-31 07:00:00+00:00,NaN,Launch Successful,Success,Russian Space Forces,...,Sun-Synchronous Orbit,SSO,43/4 (43R),"Plesetsk Cosmodrome, Russian Federation",Russia,62.928830,40.457098,2024,10,4
311,294245b7-cf76-41ad-a014-a3899783f560,Long March 4B | CBERS-3,NaN,2013-12-09 03:26:00+00:00,2013-12-09 03:26:00+00:00,2013-12-09 03:26:00+00:00,NaN,Launch Failure,Failure,China Aerospace Science and Technology Corpora...,...,Sun-Synchronous Orbit,SSO,Launch Complex 9,"Taiyuan Satellite Launch Center, People's Repu...",China,38.863128,111.589567,2013,12,4